services:
  philter-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: philter-web-app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8001}:${APP_PORT:-8001}"
    restart: unless-stopped
